# Build settings
google_analytics: true
markdown: kramdown
include: 
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
plugins:
  - jekyll-tidy
sass:
  style: expanded
directory:
  - name: About
    url: '#'
  - name: Schedule
    url: '#'
  - name: Music
    url: '#'
  - name: Contact
    url: '#'
social:
  - name: Facebook
    icon: facebook-f
    url: https://www.facebook.com/StanfordFleetStreetSingers/?fref=ts
    color: 3b5998
  - name: Twitter
    url: https://twitter.com/StanfordFleetSt
    icon: twitter
    color: 1da1f2
  - name: Youtube
    url: https://www.youtube.com/user/FleetStreetSingers
    icon: youtube
    color: ff0000
  - name: Spotify
    url: https://open.spotify.com/artist/56MfXqkYeRrlMzLhBMg9CG
    icon: spotify
    color: 1db954
  - name: iTunes
    icon: itunes-note
    url: https://itunes.apple.com/us/artist/stanford-fleet-street-singers/4165870
    color: 0070c9
  - name: Instagram
    url: https://www.instagram.com/thefleetstagram/
    icon: instagram
    color: 833ab4