# Build settings
google_analytics: true
include: 
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
plugins:
  - jekyll-tidy
markdown: kramdown
highlighter: none
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  style: expanded
defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"