# Build settings
google_analytics: true
markdown: kramdown
include: 
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
plugins:
  - jekyll-tidy
sass:
  style: expanded
defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"